Snorktracker: tracker/Utils.h File Reference
Utils.h File Reference
Data Structures
class SerialOut
Macros
#define POLY 0xedb88320
CRC-32 (Ethernet, ZIP, etc.) polynomial in reversed bit order.
Functions
long secondsSincePowerOn ()
bool secondsElapsed (long &lastCheckSec, const long &intervalSec)
bool secondsElapsedAndUpdate (long &lastCheckSec, const long &intervalSec)
long crc32 (long crc, unsigned char *buf, size_t len)
void myDebugInfo (String info, bool isWebServer, bool newline)
void MyDbg (String info, bool fromWebServer=false, bool newline=true)
void myDelayLoop ()
void MyDelay (long millisDelay)
String WifiGetRssiAsQuality (int rssi)
String TextToUrl (String data)
String TextToXml (String data)
String Trim (const String &data, const String &chars)
String formatInterval (long secs)
bool scanInterval (String interval, long &secs)
void SetupOTA ()
Detailed Description
A collection of utility functions.
Definition in file Utils.h.
Function Documentation
long crc32 (long crc, unsigned char * buf, size_t len)
Simple crc function. Can multiple called but the first time crc should be 0.
Definition at line 77 of file Utils.h.
References POLY.
Referenced by MyData::RtcData::getCRC().
 {
    crc = ~crc;
    while (len--) {
       crc ^= *buf++;
       for (int k = 0; k < 8; k++)
          crc = crc & 1 ? (crc >> 1) ^ POLY : crc >> 1;
    }
    return ~crc;
 }
String formatInterval (long secs)
Helper function to format seconds to x days hours:minutes:seconds
Definition at line 191 of file Utils.h.
Referenced by MyMqtt::handleClient(), MyWebServer::handleLoadInfoInfo(), MyWebServer::handleLoadMainInfo(), and MyWebServer::handleLoadSettingsInfo().
 {
    char buff[255];
    int days    =  secs / 60 / 60 / 24;
    int hours   = (secs / 60 / 60) % 24;
    int minutes = (secs / 60) % 60;
    int seconds =  secs % 60;
    buff[0] = '\0';
    if (days <= 0) {
       sprintf(buff, "%02d:%02d:%02d", hours, minutes, seconds);
    } else {
       sprintf(buff, "%d %02d:%02d:%02d", days, hours, minutes, seconds);
    }
    return buff;
 }
void MyDbg (String info, bool fromWebServer = false, bool newline = true)
Short version of myDebugInfo. fromWebServer prevents recursive calls when from WebServer
Definition at line 94 of file Utils.h.
References myDebugInfo().
Referenced by MyGsmPower::begin(), MyDeepSleep::begin(), MyVoltage::begin(), MyGsmGps::begin(), MySmsCmd::begin(), MyMqtt::begin(), MyWebServer::begin(), MySmsCmd::checkSms(), MySmsCmd::cmdPsm(), MyGsmGps::deleteSMS(), MyGsmGps::enableGps(), MyGsmGps::getGps(), MyGsmGps::getGpsFromGsm(), MyGsmGps::getSMS(), MyGsmGps::handleClient(), MyMqtt::handleClient(), MyWebServer::handleLoadConsoleInfo(), MyWebServer::handleLoadSettingsInfo(), MyWebServer::handleNotFound(), MyWebServer::handleSaveSettings(), MyOptions::load(), MyWebServer::loadRestart(), MyMqtt::mqttCallback(), MyMqtt::myPublish(), MyMqtt::mySubscribe(), MyGsmPower::off(), MyGsmPower::on(), readFromSpiffs(), MyBME280::readValues(), MyVoltage::readVoltage(), MyOptions::save(), MyGsmGps::sendAT(), MyGsmGps::sendSMS(), setup(), SetupOTA(), MyDeepSleep::sleep(), MyGsmGps::sleepMode2(), and MyGsmGps::stop().
 {
    myDebugInfo(info, fromWebServer, newline);
 }
void myDebugInfo (String info, bool fromWebserver, bool newline)
This function has to be overwritten to implement the handle of debug informations.
Overwritten Debug Function It logs all the debug calls to the console string-list And call a refresh of the webserver for not blocking the system.
Definition at line 92 of file tracker.ino.
References StringList::addTail(), MyWebServer::handleClient(), MyData::logInfos, myWebServer, StringList::removeTail(), secondsSincePowerOn(), and yield().
Referenced by MyDbg().
 {
    static bool lastNewLine = true;
    if (newline || lastNewLine != newline) {
       String secs = String(secondsSincePowerOn()) + F(": ");
       myData.logInfos.addTail(secs + info);
       if (!lastNewLine) {
          Serial.println("");
       }
       Serial.println(secs + info);
    } else {
       String tmp = myData.logInfos.removeTail();
       Serial.print(tmp + info);
       myData.logInfos.addTail(tmp + info);
    }
    lastNewLine = newline;
    if (!fromWebserver) {
       myWebServer.handleClient();
       myWebServer.handleClient();
       myWebServer.handleClient();
    }
    delay(1);
    yield();
 }
void MyDelay (long millisDelay)
Replacement with background calls when we have to wait. Replace the delay function.
Definition at line 104 of file Utils.h.
References myDelayLoop(), and yield().
Referenced by MyGsmGps::begin(), MyWebServer::begin(), MyMqtt::handleClient(), MyWebServer::loadRestart(), and MyGsmPower::on().
 {
    long m = millis();
    while (millis() - m < millisDelay) {
       myDelayLoop();
       yield();
       delay(1);
    }
 }
void myDelayLoop ()
This function has to be overwritten to implement background delay calls.
Overwritten delay loop for refreshing the webserver on waiting processes.
Definition at line 122 of file tracker.ino.
References MyWebServer::handleClient(), myWebServer, and yield().
Referenced by MyDelay().
 {
    myWebServer.handleClient();
    myWebServer.handleClient();
    myWebServer.handleClient();
    delay(1);
    yield();
 }
bool scanInterval (String interval, long & secs)
Helper function to scan a interval information '[days] hours:minutes:seconds'
Definition at line 210 of file Utils.h.
References Trim().
Referenced by MyWebServer::GetOption().
 {
    int first = -1;
    interval = Trim(interval, F(" "));
    first    = interval.indexOf(F(":"));
    if (first != -1) {
       String daysString;
       String hoursString;
       String minutesString;
       String secondsString;
       long   days    = 0;
       long   hours   = 0;
       long   minutes = 0;
       long   seconds = 0;
       int second = interval.indexOf(F(":"), first + 1);
       if (second != -1) {
          int space = interval.indexOf(F(" "));
          if (space != -1 && space < first) {
             daysString  = interval.substring(0, space);
             hoursString = interval.substring(space + 1, first);
          } else {
             hoursString = interval.substring(0, first);
          }
          minutesString = interval.substring(first + 1, second);
          secondsString = interval.substring(second + 1);
          days    = atol(daysString.c_str());
          hours   = atol(hoursString.c_str());
          minutes = atol(minutesString.c_str());
          seconds = atol(secondsString.c_str());
          if (days    >= 0 &&
              hours   >= 0 && hours   <= 23 &&
              minutes >= 0 && minutes <= 59 &&
              seconds >= 0 && seconds <= 59) {
             secs = 0;
             secs += days    * 24 * 60 * 60;
             secs += hours   * 60 * 60;
             secs += minutes * 60;
             secs += seconds;
             return true;
          }
       }
    }
    return false;
 }
bool secondsElapsed (long & lastCheckSec, const long & intervalSec)
Checks if the intervalSec is from the last checkIntervalSec elapsed
Definition at line 52 of file Utils.h.
References secondsSincePowerOn().
Referenced by MyGsmGps::handleClient(), MyMqtt::handleClient(), and MyMqtt::waitingForMqtt().
 {
    long currentSec = secondsSincePowerOn();
    if (lastCheckSec == 0 || (currentSec - lastCheckSec > intervalSec)) {
       return true;
    }
    return false;
 }
bool secondsElapsedAndUpdate (long & lastCheckSec, const long & intervalSec)
Checks if the intervalSec is from the last checkIntervalSec elapsed and if true it sets the lastCheckSec value
Definition at line 63 of file Utils.h.
References secondsSincePowerOn().
Referenced by MyGsmGps::handleClient(), MySmsCmd::handleClient(), and MyBME280::readValues().
 {
    long currentSec = secondsSincePowerOn();
    if (lastCheckSec == 0 || (currentSec - lastCheckSec > intervalSec)) {
       lastCheckSec = currentSec;
       return true;
    }
    return false;
 }
long secondsSincePowerOn ()
This function has to be overwritten to return the seconds since power up (not since last deep sleep).
Returns the seconds since power up (not since last deep sleep).
Definition at line 132 of file tracker.ino.
References MyData::secondsSincePowerOn().
Referenced by MyDeepSleep::begin(), MyGsmGps::getGps(), MyGsmGps::getGpsFromGsm(), MyGsmGps::handleClient(), MyMqtt::handleClient(), MyDeepSleep::haveToSleep(), myDebugInfo(), secondsElapsed(), secondsElapsedAndUpdate(), and MyDeepSleep::sleep().
 {
    return myData.secondsSincePowerOn();
 }
void SetupOTA ()
Helper function to start the OTA functionality of the ESP.
Definition at line 264 of file Utils.h.
References MyDbg().
Referenced by MyWebServer::loadUpdate().
 {
    MyDbg(F("StartOTA"));
    ArduinoOTA.setHostname("SnorkTracker");
    ArduinoOTA.setPort(8266);
    ArduinoOTA.onStart([]() {
       MyDbg(F("OTA Start"));
    });
    ArduinoOTA.onEnd([]() {
       MyDbg(F("\nOTA End"));
    });
    ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
       MyDbg("OTA Progress: " + String(progress / (total / 100)));
    });
    ArduinoOTA.onError([](ota_error_t error) {
       MyDbg("OTA Error[%u]: " + error);
       if (error == OTA_AUTH_ERROR)         MyDbg(F("OTA Auth Failed"));
       else if (error == OTA_BEGIN_ERROR)   MyDbg(F("OTA Begin Failed"));
       else if (error == OTA_CONNECT_ERROR) MyDbg(F("OTA Connect Failed"));
       else if (error == OTA_RECEIVE_ERROR) MyDbg(F("OTA Receive Failed"));
       else if (error == OTA_END_ERROR)     MyDbg(F("OTA End Failed"));
    });
 }
String TextToUrl (String data)
Convert Text to html - URL. Should be decoded with encodeURIComponent() in JavaScript And replace every invalid xml char with '?'.
Definition at line 137 of file Utils.h.
Referenced by MyWebServer::handleLoadConsoleInfo().
 {
    data.replace(F("%"), F("%25"));
    data.replace(F("&"), F("%26"));
    data.replace(F("<"), F("%3C"));
    data.replace(F(">"), F("%3E"));
    for (int i = 0; i < data.length(); i++) {
       bool validChar = (data[i] == 0x09 || data[i] == 0x0A || data[i] == 0x0D || (data[i] >= 0x20 && data[i] <= 0xFF));
       if (!validChar) {
          data[i] = '?';
       }
    }
    return data;
 }
String TextToXml (String data)
Helper HTML text conversation function for special character.
Definition at line 156 of file Utils.h.
Referenced by MyWebServer::AddIntervalInfo(), MyWebServer::AddOption(), and MyWebServer::AddTableTr().
 {
    data.replace(F("&"),  F("&amp;"));
    data.replace(F("<"),  F("&lt;"));
    data.replace(F(">"),  F("&gt;"));
    data.replace(F("\""), F("&quot;"));
    return data;
 }
String Trim (const String & data, const String & chars)
Trims the data string on the left and right side every occurrence of a char from chars.
Definition at line 168 of file Utils.h.
Referenced by MyGsmSim808::getSMS(), and scanInterval().
 {
    String ret = data;
    for (int i = 0; i < ret.length(); i++) {
       if (chars.indexOf(ret[i]) != -1) {
          ret.remove(i, 1);
          i--;
          continue;
       }
       break;
    }
    for (int i = data.length() - 1; i >= 0; i--) {
       if (chars.indexOf(ret[i]) != -1) {
          ret.remove(i, 1);
          continue;
       }
       break;
    }
    return ret;
 }
String WifiGetRssiAsQuality (int rssi)
Conversion of the RSSI value to a quality value.
Definition at line 119 of file Utils.h.
Referenced by MyWebServer::begin(), MyMqtt::handleClient(), MyWebServer::handleLoadInfoInfo(), and MyWebServer::handleLoadMainInfo().
 {
    int quality = 0;
    if (rssi <= -100) {
       quality = 0;
    } else if (rssi >= -50) {
       quality = 100;
    } else {
       quality = 2 * (rssi + 100);
    }
    return String(quality);
 }