Snorktracker: MyDegrees Class Reference
MyDegrees Class Reference
#include <Gps.h>
Public Member Functions
MyDegrees ()
MyDegrees (const MyDegrees &myDegrees)
void clear ()
double value ()
bool set (const String &data)
Data Fields
uint16_t predecimal
Value on the left side of the separator.
uint32_t billionths
Value of the right side after the separator.
bool negative
Is the value negative?
Detailed Description
Class to store the gps values with the right precision.
Definition at line 26 of file Gps.h.
Constructor & Destructor Documentation
MyDegrees::MyDegrees ()
Constructor
Definition at line 185 of file Gps.h.
    : predecimal(0)
    , billionths(0)
    , negative(false)
 {
 }
MyDegrees::MyDegrees (const MyDegrees & myDegrees)
Constructor
Definition at line 193 of file Gps.h.
    : predecimal(myDegrees.predecimal)
    , billionths(myDegrees.billionths)
    , negative(myDegrees.negative)
 {
 }
Member Function Documentation
void MyDegrees::clear ()
Reset the values.
Definition at line 201 of file Gps.h.
References billionths, negative, and predecimal.
Referenced by MyLocation::clear().
 {
    predecimal = 0;
    billionths = 0;
    negative   = false;
 }
bool MyDegrees::set (const String & data)
Sets the internal format from the nmea format.
Definition at line 217 of file Gps.h.
References billionths, negative, and predecimal.
Referenced by MyGps::setLatitude(), and MyGps::setLongitude().
 {
    const char *term          = data.c_str();
    uint32_t    multiplier    = 1000000000UL;
    uint32_t    leftOfDecimal = (uint32_t) atol(term);
    predecimal = (int16_t)leftOfDecimal;
    billionths = 0;
    while (isdigit(*term)) {
       ++term;
    }
    if (*term == '.') {
       while (isdigit(*++term)) {
          multiplier /= 10;
          billionths += (*term - '0') * multiplier;
       }
    }
    negative = false;
    return true;
 }
double MyDegrees::value ()
Recalculate the value from the pre and post decimal to double.
Definition at line 209 of file Gps.h.
References billionths, negative, and predecimal.
Referenced by MyLocation::latitude(), and MyLocation::longitude().
 {
    double ret = predecimal + billionths / 1000000000.0;
    return negative ? -ret : ret;
 }
The documentation for this class was generated from the following file:
tracker/Gps.h