Snorktracker: MyMqtt Class Reference
MyMqtt Class Reference
#include <Mqtt.h>
Public Member Functions
MyMqtt (Client &client, MyOptions &options, MyData &data)
bool begin ()
void handleClient ()
bool waitingForMqtt ()
Static Public Member Functions
static void mqttCallback (char *topic, byte *payload, unsigned int len)
Protected Member Functions
bool mySubscribe (String subTopic)
bool myPublish (String subTopic, String value)
Protected Attributes
MyOptions & myOptions
Reference to the options.
MyData & myData
Reference to the data.
bool publishInProgress
Are we publishing right now.
Static Protected Attributes
static MyOptions * g_myOptions = NULL
Static option pointer for the callback function.
Detailed Description
MQTT client for sending the collected data to a MQTT server
Definition at line 54 of file Mqtt.h.
Constructor & Destructor Documentation
MyMqtt::MyMqtt (Client & client, MyOptions & options, MyData & data)
Constructor/Destructor
Definition at line 84 of file Mqtt.h.
References g_myOptions.
    : PubSubClient(client)
    , myOptions(options)
    , myData(data)
    , publishInProgress(false)
 {
    g_myOptions = &options;
 }
Member Function Documentation
bool MyMqtt::begin ()
Sets the MQTT server settings
Definition at line 152 of file Mqtt.h.
References mqttCallback(), MyOptions::mqttPort, MyOptions::mqttServer, MyDbg(), and myOptions.
Referenced by setup().
 {
    MyDbg(F("MQTT:begin"), true);
    PubSubClient::setServer(myOptions.mqttServer.c_str(), myOptions.mqttPort);
    PubSubClient::setCallback(mqttCallback);
    return true;
 }
void MyMqtt::handleClient ()
Connect To the MQTT server and send the data when the time is right.
Definition at line 161 of file Mqtt.h.
References MyData::batteryLevel, MyData::batteryVolt, formatInterval(), MyData::getActiveTimeSec(), MyGps::getAsGpsJson(), MyData::getLowPowerPowerConsumption(), MyData::getPowerConsumption(), MyData::humidity, MyData::isGsmActive, MyData::isMoving, MyData::RtcData::lastGps, MyData::RtcData::lastMqttPublishSec, MyData::movingDistance, MyData::RtcData::mqttLastSentTime, MyOptions::mqttName, MyOptions::mqttPassword, MyData::RtcData::mqttSendCount, MyOptions::mqttSendOnMoveEverySec, MyOptions::mqttSendOnNonMoveEverySec, MyOptions::mqttUser, myData, MyDbg(), MyDelay(), myOptions, myPublish(), MyData::pressure, publishInProgress, MyData::rtcData, secondsElapsed(), secondsSincePowerOn(), MyData::signalQuality, MyData::temperature, MyGps::time, topic_alive, topic_batt_level, topic_batt_volt, topic_gps, topic_gps_distance, topic_humidity, topic_mAh, topic_mAhLowPower, topic_pressure, topic_rssi, topic_signal_quality, topic_temperature, topic_voltage, MyData::voltage, and WifiGetRssiAsQuality().
Referenced by loop().
 {
    if (!myData.isGsmActive) {
       return;
    }
    bool send = false;
    if (myData.isMoving) {
       send = secondsElapsed(myData.rtcData.lastMqttPublishSec, myOptions.mqttSendOnMoveEverySec);
    } else {
       send = secondsElapsed(myData.rtcData.lastMqttPublishSec, myOptions.mqttSendOnNonMoveEverySec);
    }
    if (send && !publishInProgress) {
       publishInProgress = true;
       if (!PubSubClient::connected()) {
          for (int i = 0; !PubSubClient::connected() && i < 5; i++) {
             MyDbg(F("Attempting MQTT connection..."), true);
             if (PubSubClient::connect(myOptions.mqttName.c_str(), myOptions.mqttUser.c_str(), myOptions.mqttPassword.c_str())) {
                // mySubscribe(topic_deep_sleep);
                // mySubscribe(topic_power_on);
 #ifdef SIM808_CONNECTED
                // mySubscribe(topic_gps_enabled);
                // mySubscribe(topic_send_on_move_every);
                // mySubscribe(topic_send_on_non_move_every);
 #endif
                MyDbg(F(" connected"), true);
             } else {
                MyDbg((String) F("   Mqtt failed, rc = ") + String(PubSubClient::state()), true);
                MyDbg(F(" Try again in 5 seconds"), true);
                MyDelay(5000);
                MyDbg(F("."), true, false);
             }
          }
       }
       if (PubSubClient::connected()) {
          char gpsJson[255];
          MyDbg(F("Attempting MQTT publishing"), true);
          myPublish(topic_voltage,     String(myData.voltage, 2));
          myPublish(topic_mAh,         String(myData.getPowerConsumption()));
          myPublish(topic_mAhLowPower, String(myData.getLowPowerPowerConsumption()));
          myPublish(topic_alive,       formatInterval(myData.getActiveTimeSec()));
 #ifndef SIM808_CONNECTED
          myPublish(topic_rssi,        WifiGetRssiAsQuality(WiFi.RSSI()));
 #endif
          myPublish(topic_temperature, String(myData.temperature));
          myPublish(topic_humidity,    String(myData.humidity));
          myPublish(topic_pressure,    String(myData.pressure));
 #ifdef SIM808_CONNECTED
          myPublish(topic_signal_quality, myData.signalQuality);
          myPublish(topic_batt_level,     myData.batteryLevel);
          myPublish(topic_batt_volt,      myData.batteryVolt);
          if (myData.rtcData.lastGps.getAsGpsJson(gpsJson)) {
             myPublish(topic_gps, gpsJson);
             myPublish(topic_gps_distance, String(myData.movingDistance));
          }
 #endif
          myData.rtcData.mqttSendCount++;
          myData.rtcData.mqttLastSentTime = myData.rtcData.lastGps.time;
          MyDbg(F("mqtt published"), true);
          MyDelay(5000);
       }
       // Set time even on error
       myData.rtcData.lastMqttPublishSec = secondsSincePowerOn();
       publishInProgress = false;
    }
 }
void MyMqtt::mqttCallback (char * topic, byte * payload, unsigned int len) static
Static function for MQTT callback on registered topics.
Definition at line 235 of file Mqtt.h.
References g_myOptions, MyOptions::isDeepSleepEnabled, MyOptions::isGpsEnabled, MyOptions::mqttName, MyOptions::mqttSendOnMoveEverySec, MyOptions::mqttSendOnNonMoveEverySec, MyDbg(), MyOptions::powerOn, topic_deep_sleep, topic_gps_enabled, topic_power_on, topic_send_every, topic_send_on_move_every, and topic_send_on_non_move_every.
Referenced by begin().
 {
    if (topic == NULL || payload == NULL || len <= 0 || len > 200) {
       return;
    }
    String strTopic = String((char*)topic);
    payload[len] = '\0';
    MyDbg((String) F("Message arrived [") + strTopic + F("]:[ "), true);
    if (len) MyDbg((char *) payload, true);
    MyDbg(F("]"), true);
    if (MyMqtt::g_myOptions) {
       if (strTopic == g_myOptions->mqttName + topic_deep_sleep) {
          g_myOptions->isDeepSleepEnabled = atoi((char *) payload);
          MyDbg(strTopic + g_myOptions->isDeepSleepEnabled ? F(" - On") : F(" - Off"), true);
       }
       if (strTopic == g_myOptions->mqttName + topic_power_on) {
          g_myOptions->powerOn = atoi((char *) payload);
          MyDbg(strTopic + g_myOptions->powerOn ? F(" - On") : F(" - Off"), true);
       }
       if (strTopic == g_myOptions->mqttName + topic_gps_enabled) {
          g_myOptions->isGpsEnabled = atoi((char *) payload);
          MyDbg(strTopic + g_myOptions->isGpsEnabled ? F(" - Enabled") : F(" - Disabled"), true);
       }
       if (strTopic == g_myOptions->mqttName + topic_send_on_move_every) {
          g_myOptions->mqttSendOnMoveEverySec = atoi((char *) payload);
          MyDbg(strTopic + " - " + String(g_myOptions->mqttSendOnMoveEverySec), true);
       }
       if (strTopic == g_myOptions->mqttName + topic_send_on_non_move_every) {
          g_myOptions->mqttSendOnNonMoveEverySec = atoi((char *) payload);
          MyDbg(strTopic + " - " + String(g_myOptions->mqttSendOnNonMoveEverySec), true);
       }
       if (strTopic == g_myOptions->mqttName + topic_send_every) {
          g_myOptions->mqttSendOnNonMoveEverySec = atoi((char *)payload);
          MyDbg(strTopic + " - " + String(g_myOptions->mqttSendOnNonMoveEverySec), true);
       }
    }
 }
bool MyMqtt::myPublish (String subTopic, String value) protected
Helper function to publish on mqtt It put the mqttName from optione before the topic.
Definition at line 116 of file Mqtt.h.
References MyData::isGsmActive, MyOptions::mqttId, MyOptions::mqttName, myData, MyDbg(), and myOptions.
Referenced by handleClient().
 {
    if (!myData.isGsmActive) {
       return false;
    }
    bool ret = false;
    if (value.length() > 0) {
       String topic;
       topic = myOptions.mqttName + F("/") + myOptions.mqttId + subTopic;
       MyDbg((String) F("MyMqtt::publish: [") + topic + F("]=[") + value + F("]"), true);
       ret = PubSubClient::publish(topic.c_str(), value.c_str(), true);
    }
    return ret;
 }
bool MyMqtt::mySubscribe (String subTopic) protected
Helper function to subscrbe on mqtt It put the mqttName and id from options before the topic.
Definition at line 100 of file Mqtt.h.
References MyData::isGsmActive, MyOptions::mqttId, MyOptions::mqttName, myData, MyDbg(), and myOptions.
 {
    if (!myData.isGsmActive) {
       return false;
    }
    String topic;
    topic = myOptions.mqttName + F("/") + myOptions.mqttId + subTopic;
    MyDbg((String) F("MyMqtt::subscribe: [") + topic + F("]"), true);
    return PubSubClient::subscribe(topic.c_str());
 }
bool MyMqtt::waitingForMqtt ()
Check if we have to wait for sending mqtt data.
Definition at line 135 of file Mqtt.h.
References MyData::isGsmActive, MyData::isMoving, MyData::RtcData::lastMqttPublishSec, MyOptions::mqttSendOnMoveEverySec, MyOptions::mqttSendOnNonMoveEverySec, myData, myOptions, publishInProgress, MyData::rtcData, and secondsElapsed().
Referenced by loop().
 {
    if (!myData.isGsmActive) {
       return false;
    }
    if (publishInProgress) {
       return true;
    }
    if (myData.isMoving) {
       return secondsElapsed(myData.rtcData.lastMqttPublishSec, myOptions.mqttSendOnMoveEverySec);
    } else {
       return secondsElapsed(myData.rtcData.lastMqttPublishSec, myOptions.mqttSendOnNonMoveEverySec);
    }
    return false;
 }
The documentation for this class was generated from the following file:
tracker/Mqtt.h