Snorktracker: MySmsCmd Class Reference
MySmsCmd Class Reference
#include <SmsCmd.h>
Public Member Functions
MySmsCmd (MyGsmGps &gsmGps, MyOptions &options, MyData &data)
bool begin ()
void handleClient ()
Protected Member Functions
void checkSms ()
String getGoogleMapGpsUrl ()
void sendSms (const String &message)
void sendOk (const SmsData &sms)
bool readValues (String &value, const String message)
bool readValues (long &value, const String message)
bool readValues (long &value, long &value2, const String message)
void cmdOn (const SmsData &sms)
void cmdOff (const SmsData &sms)
void cmdStatus (const SmsData &sms)
void cmdPsm (const SmsData &sms)
void cmdGps (const SmsData &sms)
void cmdSms (const SmsData &sms)
void cmdMqtt (const SmsData &sms)
void cmdPhone (const SmsData &sms)
void cmdDefault (const SmsData &sms)
Protected Attributes
MyGsmGps & myGsmGps
Reference to the gsm/gps instance.
MyOptions & myOptions
Reference to the options.
MyData & myData
Reference to the data.
Detailed Description
SMS Controller class to manage receiving SMS commands.
Definition at line 26 of file SmsCmd.h.
Constructor & Destructor Documentation
MySmsCmd::MySmsCmd (MyGsmGps & gsmGps, MyOptions & options, MyData & data)
Constructor
Definition at line 65 of file SmsCmd.h.
    : myGsmGps(gsmGps)
    , myOptions(options)
    , myData(data)
 {
 }
Member Function Documentation
bool MySmsCmd::begin ()
Log only the start of the sms controller
Definition at line 73 of file SmsCmd.h.
References MyDbg().
Referenced by setup().
 {
    MyDbg(F("MySmsCmd::begin"));
    return true;
 }
void MySmsCmd::checkSms () protected
Checks for new sms and parse the commands from the message
Definition at line 102 of file SmsCmd.h.
References cmdDefault(), cmdGps(), cmdMqtt(), cmdOff(), cmdOn(), cmdPhone(), cmdPsm(), cmdSms(), cmdStatus(), MyGsmGps::deleteSMS(), MyGsmGps::getSMS(), SmsData::index, MyData::isGsmActive, SmsData::message, myData, MyDbg(), myGsmGps, and SmsData::phoneNumber.
Referenced by handleClient().
 {
    if (!myData.isGsmActive) {
       return;
    }
    SmsData sms;
    MyDbg(F("checkSMS"));
    while (myGsmGps.getSMS(sms)) {
       String messageLower = sms.message;
       messageLower.toLowerCase();
       myGsmGps.deleteSMS(sms.index);
       MyDbg((String) F("SMS: ") + sms.message + F(" [") + sms.phoneNumber + F("]"));
       if (messageLower.indexOf(F("on")) == 0) {
          cmdOn(sms);
       } else if (messageLower.indexOf(F("off")) == 0) {
          cmdOff(sms);
       } else if (messageLower.indexOf(F("status")) == 0) {
          cmdStatus(sms);
       } else if (messageLower.indexOf(F("psm")) == 0) {
          cmdPsm(sms);
       } else if (messageLower.indexOf(F("gps")) == 0) {
          cmdGps(sms);
       } else if (messageLower.indexOf(F("sms")) == 0) {
          cmdSms(sms);
       } else if (messageLower.indexOf(F("mqtt")) == 0) {
          cmdMqtt(sms);
       } else if (messageLower.indexOf(F("phone")) == 0) {
          cmdPhone(sms);
       } else {
          cmdDefault(sms);
       }
    }
 }
void MySmsCmd::cmdDefault (const SmsData & sms) protected
Default sms response if something is wrong
Definition at line 302 of file SmsCmd.h.
References sendSms().
Referenced by checkSms(), cmdGps(), cmdMqtt(), cmdPhone(), cmdPsm(), and cmdSms().
 {
    String info;
    info += F("wrong command\n");
    info += F("on\n");
    info += F("off\n");
    info += F("status\n");
    info += F("psm[:off] - power saving mode\n");
    info += F("gps[:15] - check every (sec)\n");
    info += F("sms[:15] - check every (sec)\n");
    info += F("mqtt[30:60] - (moving:standing (sec)\n");
    info += F("phone:1234\n");
    sendSms(info);
 }
void MySmsCmd::cmdGps (const SmsData & sms) protected
Command: send the gps position as an google map URL.
Definition at line 258 of file SmsCmd.h.
References cmdDefault(), getGoogleMapGpsUrl(), MyOptions::gpsCheckIntervalSec, SmsData::message, myOptions, readValues(), sendOk(), and sendSms().
Referenced by checkSms().
 {
    if (sms.message.indexOf(F(":")) == -1) {
       sendSms(getGoogleMapGpsUrl());
    } else {
       if (readValues(myOptions.gpsCheckIntervalSec, sms.message)) {
          sendOk(sms);
       } else {
          cmdDefault(sms);
       }
    }
 }
void MySmsCmd::cmdMqtt (const SmsData & sms) protected
Command: Set the mqtt sending time checking time values.
Definition at line 282 of file SmsCmd.h.
References cmdDefault(), SmsData::message, MyOptions::mqttSendOnMoveEverySec, MyOptions::mqttSendOnNonMoveEverySec, myOptions, readValues(), and sendOk().
Referenced by checkSms().
 {
    if (readValues(myOptions.mqttSendOnMoveEverySec, myOptions.mqttSendOnNonMoveEverySec, sms.message)) {
       sendOk(sms);
    } else {
       cmdDefault(sms);
    }
 }
void MySmsCmd::cmdOff (const SmsData & sms) protected
Command: switch off the modules
Definition at line 204 of file SmsCmd.h.
References myOptions, MyOptions::powerOn, MyOptions::save(), and sendOk().
Referenced by checkSms().
 {
    myOptions.powerOn = false;
    myOptions.save();
    sendOk(sms);
 }
void MySmsCmd::cmdOn (const SmsData & sms) protected
Command: switch on the modules
Definition at line 195 of file SmsCmd.h.
References MyOptions::isGpsEnabled, myOptions, MyOptions::powerOn, MyOptions::save(), and sendOk().
Referenced by checkSms().
 {
    myOptions.powerOn      = true;
    myOptions.isGpsEnabled = true;
    myOptions.save();
    sendOk(sms);
 }
void MySmsCmd::cmdPhone (const SmsData & sms) protected
Command: Set the receiving phone number.
Definition at line 292 of file SmsCmd.h.
References cmdDefault(), SmsData::message, myOptions, MyOptions::phoneNumber, readValues(), and sendOk().
Referenced by checkSms().
 {
    if (readValues(myOptions.phoneNumber, sms.message)) {
       sendOk(sms);
    } else {
       cmdDefault(sms);
    }
 }
void MySmsCmd::cmdPsm (const SmsData & sms) protected
Command: switch the power saving mode on or off.
Definition at line 237 of file SmsCmd.h.
References cmdDefault(), MyOptions::isDeepSleepEnabled, SmsData::message, MyDbg(), myOptions, readValues(), MyOptions::save(), and sendOk().
Referenced by checkSms().
 {
    if (sms.message.indexOf(F(":")) == -1) {
       myOptions.isDeepSleepEnabled = true;
       myOptions.save();
       sendOk(sms);
    } else {
       String off;
       if (readValues(off, sms.message) && off == F("off")) {
          myOptions.isDeepSleepEnabled = true;
          myOptions.save();
          sendOk(sms);
       } else {
          MyDbg((String) F("psm:[") + off + F("]"));
          cmdDefault(sms);
       }
    }
 }
void MySmsCmd::cmdSms (const SmsData & sms) protected
Command: Set the sms checking time.
Definition at line 272 of file SmsCmd.h.
References cmdDefault(), SmsData::message, myOptions, readValues(), sendOk(), and MyOptions::smsCheckIntervalSec.
Referenced by checkSms().
 {
    if (readValues(myOptions.smsCheckIntervalSec, sms.message)) {
       sendOk(sms);
    } else {
       cmdDefault(sms);
    }
 }
void MySmsCmd::cmdStatus (const SmsData & sms) protected
Command: send status information via sms
Definition at line 212 of file SmsCmd.h.
References MyGps::altitudeString(), MyGps::fixStatus, getGoogleMapGpsUrl(), MyData::humidity, MyOptions::isGpsEnabled, MyGps::kmphString(), MyData::RtcData::lastGps, myData, myOptions, MyData::pressure, MyData::rtcData, MyGps::satellitesString(), sendSms(), MyData::status, MyData::temperature, and MyData::voltage.
Referenced by checkSms().
 {
    String status;
    status += (String) F("Status: ")      + myData.status              + '\n';
    status += (String) F("Voltage: ")     + String(myData.voltage, 2)  + F(" V\n");
    status += (String) F("Temperature: ") + String(myData.temperature) + F(" C\n");
    status += (String) F("Humidity: ")    + String(myData.humidity)    + F(" %\n");
    status += (String) F("Pressure: ")    + String(myData.pressure)    + F(" hPa\n");
    if (!myData.rtcData.lastGps.fixStatus) {
       if (myOptions.isGpsEnabled) {
          status += F("No Gps positions.");
       } else {
          status += F("Gps not enabled.");
       }
    } else {
       status += (String) F("Altitude: ")   + myData.rtcData.lastGps.altitudeString()   + F(" m\n");
       status += (String) F("Speed: ")      + myData.rtcData.lastGps.kmphString()       + F(" kmph\n");
       status += (String) F("Satellites: ") + myData.rtcData.lastGps.satellitesString() + '\n';
       status += getGoogleMapGpsUrl();
    }
    sendSms(status);
 }
String MySmsCmd::getGoogleMapGpsUrl () protected
Returns the gps position as an google map url.
Definition at line 88 of file SmsCmd.h.
References MyGps::fixStatus, MyOptions::isGpsEnabled, MyData::RtcData::lastGps, MyGps::latitudeString(), MyGps::longitudeString(), myData, myOptions, and MyData::rtcData.
Referenced by cmdGps(), and cmdStatus().
 {
    if (myData.rtcData.lastGps.fixStatus) {
       return (String) F("https://maps.google.com/maps?q=") + myData.rtcData.lastGps.latitudeString() + F(",") + myData.rtcData.lastGps.longitudeString();
    } else {
       if (myOptions.isGpsEnabled) {
          return F("No Gps position.\n");
       } else {
          return F("Gps not enabled.\n");
       }
    }
 }
void MySmsCmd::handleClient ()
Check the sms if the time from the options is elapsed.
Definition at line 80 of file SmsCmd.h.
References checkSms(), MyData::RtcData::lastSmsCheckSec, myData, myOptions, MyData::rtcData, secondsElapsedAndUpdate(), and MyOptions::smsCheckIntervalSec.
Referenced by loop().
 {
    if (secondsElapsedAndUpdate(myData.rtcData.lastSmsCheckSec, myOptions.smsCheckIntervalSec)) {
       checkSms();
    }
 }
bool MySmsCmd::readValues (String & value, const String message) protected
Parse a sub string parameter from a sms message (xxx:sub)
Definition at line 153 of file SmsCmd.h.
Referenced by cmdGps(), cmdMqtt(), cmdPhone(), cmdPsm(), and cmdSms().
 {
    int idx = message.indexOf(':');
    if (idx != -1) {
       value = message.substring(idx + 1);
       value.toLowerCase();
       return true;
    }
    return false;
 }
bool MySmsCmd::readValues (long & value, const String message) protected
Parse a sub long parameter from a sms message (xxx:sub)
Definition at line 166 of file SmsCmd.h.
 {
    int idx = message.indexOf(':');
    if (idx != -1) {
       value = atoi(message.substring(idx + 1).c_str());
       return true;
    }
    return false;
 }
bool MySmsCmd::readValues (long & value1, long & value2, const String message) protected
Parse two sub long parameter from a sms message (xxx:sub1:sub2)
Definition at line 178 of file SmsCmd.h.
 {
    int first = message.indexOf(':');
    if (first != -1) {
       int second = message.indexOf(':', first + 1);
       if (second != -1) {
          value1 = atoi(message.substring(first + 1, second).c_str());
          value2 = atoi(message.substring(second + 1).c_str());
          return true;
       }
    }
    return false;
 }
void MySmsCmd::sendOk (const SmsData & sms) protected
Send an OK sms
Definition at line 147 of file SmsCmd.h.
References SmsData::message, and sendSms().
Referenced by cmdGps(), cmdMqtt(), cmdOff(), cmdOn(), cmdPhone(), cmdPsm(), and cmdSms().
 {
    sendSms(sms.message + F(" -> OK"));
 }
void MySmsCmd::sendSms (const String & message) protected
Helper function to send one sms
Definition at line 141 of file SmsCmd.h.
References myGsmGps, myOptions, MyOptions::phoneNumber, and MyGsmGps::sendSMS().
Referenced by cmdDefault(), cmdGps(), cmdStatus(), and sendOk().
 {
    myGsmGps.sendSMS(myOptions.phoneNumber, message);
 }
The documentation for this class was generated from the following file:
tracker/SmsCmd.h