Snorktracker: MyGps Class Reference
MyGps Class Reference
#include <Gps.h>
Public Member Functions
MyGps ()
void clear ()
bool setRunStatus (const String &data)
bool setFixStatus (const String &data)
bool setDateTime (const String &data)
bool setLatitude (const String &data)
bool setLongitude (const String &data)
bool setAltitude (const String &data)
bool setSpeed (const String &data)
bool setCourse (const String &data)
bool setFixMode (const String &data)
bool setHdop (const String &data)
bool setPdop (const String &data)
bool setVdop (const String &data)
bool setSatellitesInView (const String &data)
bool setSatellitesUsed (const String &data)
String longitudeString ()
String latitudeString ()
String altitudeString ()
String kmphString ()
String satellitesString ()
String courseString ()
bool getAsGpsJson (char *gpsJson)
Data Fields
bool runStatus
Is the gps modul running?
bool fixStatus
Are the gps is valid received?
MyDate date
The received gps utc date.
MyTime time
The received gps utc time.
MyLocation location
The gps position.
double altitude
The current height.
double speed
The detected moving speed.
double course
The calculated course.
int fixMode
Precission of the gps data.
double pdop
Dilution of precision.
double hdop
Horizontal dilution of precision.
double vdop
Vertical dilution of precision.
int satellitesInView
Sattelites in the View.
int satellitesUsed
Sattelites used for gps position.
Protected Member Functions
bool parse (bool &b, const String &data)
bool parse (int &i, const String &data)
bool parse (double &d, const String &data)
Detailed Description
GPS data class with all the data items from the GPS message from the SIM808 module
Definition at line 129 of file Gps.h.
Constructor & Destructor Documentation
MyGps::MyGps ()
Constructor
Definition at line 392 of file Gps.h.
    : runStatus(false)
    , fixStatus(false)
    , altitude(0)
    , speed(0)
    , course(0)
    , fixMode(0)
    , hdop(0)
    , pdop(0)
    , vdop(0)
    , satellitesInView(0)
    , satellitesUsed(0)
 {
 }
Member Function Documentation
String MyGps::altitudeString ()
Returns the altitude as a string
Definition at line 552 of file Gps.h.
References altitude.
Referenced by MySmsCmd::cmdStatus(), getAsGpsJson(), MyGsmGps::getGps(), MyWebServer::handleLoadInfoInfo(), and MyWebServer::handleLoadMainInfo().
 {
    return String(altitude, 0);
 }
void MyGps::clear ()
Reset the values.
Definition at line 408 of file Gps.h.
References altitude, MyLocation::clear(), MyDate::clear(), MyTime::clear(), course, date, fixMode, fixStatus, hdop, location, pdop, runStatus, satellitesInView, satellitesUsed, speed, time, and vdop.
Referenced by MyGsmSim808::getGps(), and MyGsmSim808::getGsmGps().
 {
    date.clear();
    time.clear();
    location.clear();
    runStatus        = false;
    fixStatus        = false;
    altitude         = 0.0;
    speed            = 0.0;
    course           = 0.0;
    fixMode          = 0;
    pdop             = 0.0;
    hdop             = 0.0;
    vdop             = 0.0;
    satellitesInView = 0;
    satellitesUsed   = 0;
 }
String MyGps::courseString ()
Returns the course as a string
Definition at line 570 of file Gps.h.
References course.
Referenced by MyGsmGps::getGps(), and MyWebServer::handleLoadInfoInfo().
 {
    return String(course);
 }
bool MyGps::getAsGpsJson (char * gpsJson)
Returns the core gps data as json array
Definition at line 576 of file Gps.h.
References altitudeString(), fixStatus, kmphString(), latitudeString(), and longitudeString().
Referenced by MyMqtt::handleClient().
 {
    if (fixStatus) {
       String gps;
       gps += "{";
       gps += "\"long\":\"" + longitudeString() + "\",";
       gps += "\"lat\":\""  + latitudeString()  + "\",";
       gps += "\"alt\":\""  + altitudeString()  + "\",";
       gps += "\"kmph\":\"" + kmphString()      + "\"";
       gps += "}";
       gps.toCharArray(gpsJson, (gps.length() + 1));
       return true;
    }
    return false;
 }
String MyGps::kmphString ()
Returns the kmph as a string
Definition at line 558 of file Gps.h.
References speed.
Referenced by MySmsCmd::cmdStatus(), getAsGpsJson(), MyGsmGps::getGps(), MyWebServer::handleLoadInfoInfo(), and MyWebServer::handleLoadMainInfo().
 {
    return String(speed, 0);
 }
String MyGps::latitudeString ()
Returns the latitude as a string
Definition at line 546 of file Gps.h.
References MyLocation::latitudeString(), and location.
Referenced by getAsGpsJson(), MySmsCmd::getGoogleMapGpsUrl(), MyGsmGps::getGps(), MyGsmGps::getGpsFromGsm(), MyWebServer::handleLoadInfoInfo(), and MyWebServer::handleLoadMainInfo().
 {
    return location.latitudeString();
 }
String MyGps::longitudeString ()
Returns the longitude as a string
Definition at line 540 of file Gps.h.
References location, and MyLocation::longitudeString().
Referenced by getAsGpsJson(), MySmsCmd::getGoogleMapGpsUrl(), MyGsmGps::getGps(), MyGsmGps::getGpsFromGsm(), MyWebServer::handleLoadInfoInfo(), and MyWebServer::handleLoadMainInfo().
 {
    return location.longitudeString();
 }
bool MyGps::parse (bool & b, const String & data) protected
Parse a bool value from a string '0' or '1'
Definition at line 427 of file Gps.h.
Referenced by setAltitude(), setCourse(), setDateTime(), setFixMode(), setFixStatus(), setHdop(), setPdop(), setRunStatus(), setSatellitesInView(), setSatellitesUsed(), setSpeed(), and setVdop().
 {
    if (data == F("0")) {
       b = false;
       return true;
    } else if (data == F("1")) {
       b = true;
       return true;
    }
    return false;
 }
bool MyGps::parse (int & i, const String & data) protected
Parse a int value from a string
Definition at line 440 of file Gps.h.
 {
     i = atol(data.c_str());
     return true;
 }
bool MyGps::parse (double & d, const String & data) protected
Parse a double value from a string
Definition at line 447 of file Gps.h.
 {
     d = atof(data.c_str());
     return true;
 }
String MyGps::satellitesString ()
Returns the satellites as a string
Definition at line 564 of file Gps.h.
References satellitesUsed.
Referenced by MySmsCmd::cmdStatus(), MyGsmGps::getGps(), MyWebServer::handleLoadInfoInfo(), and MyWebServer::handleLoadMainInfo().
 {
    return String(satellitesUsed);
 }
bool MyGps::setAltitude (const String & data)
Sets the altitude from the data string
Definition at line 486 of file Gps.h.
References altitude, and parse().
Referenced by MyGsmSim808::getGps().
 {
    return parse(altitude, data);
 }
bool MyGps::setCourse (const String & data)
Sets the course value from the data string
Definition at line 498 of file Gps.h.
References course, and parse().
Referenced by MyGsmSim808::getGps().
 {
    return parse(course, data);
 }
bool MyGps::setDateTime (const String & data)
Sets the date and time from the data string
Definition at line 466 of file Gps.h.
References MyDate::date, date, parse(), MyTime::time, and time.
Referenced by MyGsmSim808::getGps(), and MyGsmSim808::getGsmGps().
 {
    parse(date.date, data.substring(0, 8));
    parse(time.time, data.substring(8));
    return true;
 }
bool MyGps::setFixMode (const String & data)
Sets the fix mode from the data string
Definition at line 504 of file Gps.h.
References fixMode, and parse().
Referenced by MyGsmSim808::getGps().
 {
    return parse(fixMode, data);
 }
bool MyGps::setFixStatus (const String & data)
Sets the fix status from the data string
Definition at line 460 of file Gps.h.
References fixStatus, and parse().
Referenced by MyGsmSim808::getGps().
 {
    return parse(fixStatus, data);
 }
bool MyGps::setHdop (const String & data)
Sets the hdop mode from the data string
Definition at line 516 of file Gps.h.
References hdop, and parse().
Referenced by MyGsmSim808::getGps().
 {
    return parse(hdop, data);
 }
bool MyGps::setLatitude (const String & data)
Set the latitude from the data string
Definition at line 474 of file Gps.h.
References MyLocation::latitude_, location, and MyDegrees::set().
Referenced by MyGsmSim808::getGps(), and MyGsmSim808::getGsmGps().
 {
    return location.latitude_.set(data);
 }
bool MyGps::setLongitude (const String & data)
Sets the longitude from the data string
Definition at line 480 of file Gps.h.
References location, MyLocation::longitude_, and MyDegrees::set().
Referenced by MyGsmSim808::getGps(), and MyGsmSim808::getGsmGps().
 {
    return location.longitude_.set(data);
 }
bool MyGps::setPdop (const String & data)
Sets the pdop mode from the data string
Definition at line 510 of file Gps.h.
References parse(), and pdop.
Referenced by MyGsmSim808::getGps().
 {
    return parse(pdop, data);
 }
bool MyGps::setRunStatus (const String & data)
Sets the run status from the data string
Definition at line 454 of file Gps.h.
References parse(), and runStatus.
Referenced by MyGsmSim808::getGps().
 {
    return parse(runStatus, data);
 }
bool MyGps::setSatellitesInView (const String & data)
Sets the satellites in view value from the data string
Definition at line 528 of file Gps.h.
References parse(), and satellitesInView.
Referenced by MyGsmSim808::getGps().
 {
    return parse(satellitesInView, data);
 }
bool MyGps::setSatellitesUsed (const String & data)
Sets the satellites used value from the data string
Definition at line 534 of file Gps.h.
References parse(), and satellitesUsed.
Referenced by MyGsmSim808::getGps().
 {
    return parse(satellitesUsed, data);
 }
bool MyGps::setSpeed (const String & data)
Sets the speed value from the data string
Definition at line 492 of file Gps.h.
References parse(), and speed.
Referenced by MyGsmSim808::getGps().
 {
    return parse(speed, data);
 }
bool MyGps::setVdop (const String & data)
Sets the vdop mode from the data string
Definition at line 522 of file Gps.h.
References parse(), and vdop.
Referenced by MyGsmSim808::getGps().
 {
    return parse(vdop, data);
 }
The documentation for this class was generated from the following file:
tracker/Gps.h