Snorktracker: MyVoltage Class Reference
MyVoltage Class Reference
#include <Voltage.h>
Public Member Functions
MyVoltage (MyOptions &options, MyData &data)
bool begin ()
void readVoltage ()
Protected Attributes
MyOptions & myOptions
Reference to global options.
MyData & myData
Reference to global data.
long lowPowerStartSec
Switch off timestamp.
Detailed Description
Voltage Reader. Works with the voltage divider resistors and the analog input reader.
Definition at line 28 of file Voltage.h.
Constructor & Destructor Documentation
MyVoltage::MyVoltage (MyOptions & options, MyData & data)
Constructor
Definition at line 47 of file Voltage.h.
    : myOptions(options)
    , myData(data)
    , lowPowerStartSec(0)
 {
 }
Member Function Documentation
bool MyVoltage::begin ()
Reads the voltage at startup.
Definition at line 55 of file Voltage.h.
References ANALOG_FACTOR, MyData::isLowPower, lowPowerStartSec, myData, MyDbg(), myOptions, MyOptions::powerSaveModeVoltage, and MyData::voltage.
Referenced by setup().
 {
    MyDbg(F("MyVoltage::begin"));
    pinMode(A0, INPUT);
    myData.voltage    = ANALOG_FACTOR * analogRead(A0); // Volt
    myData.isLowPower = myData.voltage < myOptions.powerSaveModeVoltage;
    lowPowerStartSec  = millis() / 1000;
 }
void MyVoltage::readVoltage ()
Reads the power supply voltage and save the value in the data class. Add the lowPower time to the lowPowerActive and lowPowerPowerOn time.
Definition at line 67 of file Voltage.h.
References ANALOG_FACTOR, MyData::isLowPower, MyData::isPowerOn, MyData::RtcData::lowPowerActiveTimeSec, MyData::RtcData::lowPowerPowerOnTimeSec, lowPowerStartSec, myData, MyDbg(), myOptions, MyOptions::powerSaveModeVoltage, MyData::rtcData, and MyData::voltage.
Referenced by loop().
 {
    bool isLowPower = false;
    long currSec    = millis() / 1000;
    myData.voltage = ANALOG_FACTOR * analogRead(A0); // Volt
    isLowPower     = myData.voltage < myOptions.powerSaveModeVoltage;
    if (myData.isLowPower && !isLowPower) { // Change to high power
       long lowPowerSec = currSec - lowPowerStartSec;
       myData.rtcData.lowPowerActiveTimeSec += lowPowerSec;
       if (myData.isPowerOn) {
          myData.rtcData.lowPowerPowerOnTimeSec += lowPowerSec;
       }
       MyDbg((String) F("Change to high power (V): ") + String(myData.voltage, 2));
    }
    if (!myData.isLowPower && isLowPower) { // Change to low power
       lowPowerStartSec = currSec;
       MyDbg((String) F("Change to low power (V): ") + String(myData.voltage, 2));
    }
    myData.isLowPower = isLowPower;
 }
The documentation for this class was generated from the following file:
tracker/Voltage.h