Snorktracker: MyGsmPower Class Reference
MyGsmPower Class Reference
#include <GsmPower.h>
Public Member Functions
MyGsmPower (MyData &data, int pin)
bool begin ()
void on ()
void off ()
Protected Attributes
MyData & myData
Reference to the data.
int pinPower
esp8266 pin connected with pin 5 of the LM2596 modul.
long powerOnStartSec
Timestamp of power on.
Detailed Description
Class to switch on/off the DC-DC modul LM2596.
Definition at line 27 of file GsmPower.h.
Constructor & Destructor Documentation
MyGsmPower::MyGsmPower (MyData & data, int pin)
Constructor
Definition at line 47 of file GsmPower.h.
    : myData(data)
    , pinPower(pin)
    , powerOnStartSec(0)
 {
 }
Member Function Documentation
bool MyGsmPower::begin ()
Set the pin mode to input -> switch off the DC-DC module
Definition at line 55 of file GsmPower.h.
References MyDbg(), and pinPower.
Referenced by setup().
 {
    MyDbg(F("MyGsmPower::begin"));
    pinMode(pinPower, INPUT);
    return true;
 }
void MyGsmPower::off ()
Switch off the DC-DC module
Definition at line 74 of file GsmPower.h.
References MyData::isPowerOn, myData, MyDbg(), pinPower, powerOnStartSec, MyData::RtcData::powerOnTimeSec, and MyData::rtcData.
Referenced by loop().
 {
    MyDbg(F("MyGsmPower::off"));
    pinMode(pinPower, INPUT);
    digitalWrite(pinPower, HIGH);
    myData.rtcData.powerOnTimeSec += millis() / 1000 - powerOnStartSec;
    myData.isPowerOn = false;
    powerOnStartSec = 0;
 }
void MyGsmPower::on ()
Switch on the DC-DC module
Definition at line 63 of file GsmPower.h.
References MyData::isPowerOn, myData, MyDbg(), MyDelay(), pinPower, and powerOnStartSec.
Referenced by loop().
 {
    MyDbg(F("MyGsmPower::on"));
    pinMode(pinPower, OUTPUT);
    digitalWrite(pinPower, LOW);
    myData.isPowerOn = true;
    powerOnStartSec  = millis() / 1000;
    MyDelay(1000);
 }
The documentation for this class was generated from the following file:
tracker/GsmPower.h