Snorktracker: MyData::RtcData Class Reference
MyData::RtcData Class Reference
#include <Data.h>
Public Member Functions
bool isValid ()
void setCRC ()
long getCRC ()
Data Fields
MyGps lastGps
Last known gps location without timeout.
long aktiveTimeSec
Time in active mode without current millis().
long powerOnTimeSec
Time the sim808 is on power without current millis..
long deepSleepTimeSec
Time in deep sleep mode.
long deepSleepStartSec
Timestamp of the last deep sleep start.
long lowPowerActiveTimeSec
Timestamp of the last deep sleep start.
long lowPowerPowerOnTimeSec
Timestamp of the last deep sleep start.
long lastBme280ReadSec
Timestamp of the last BME280 read.
long lastSmsCheckSec
Timestamp of the last sms check.
long lastGpsReadSec
Timestamp of the last gps read.
long lastMqttPublishSec
Timestamp from the last send.
long mqttSendCount
How many time the mqtt data successfully sent.
long mqttLastSentTime
Last mqtt sent timestamp.
long crcValue
CRC of the RtcData.
Detailed Description
Data to store in the RTC memory
Definition at line 33 of file Data.h.
Member Function Documentation
long MyData::RtcData::getCRC ()
Creates a CRC of all the member variables.
Definition at line 145 of file Data.h.
References crc32().
Referenced by isValid().
 {
    long crc = 0;
    crc = crc32(crc, (unsigned char *) &lastGps,                sizeof(MyGps));
    crc = crc32(crc, (unsigned char *) &aktiveTimeSec,          sizeof(long));
    crc = crc32(crc, (unsigned char *) &powerOnTimeSec,         sizeof(long));
    crc = crc32(crc, (unsigned char *) &deepSleepTimeSec,       sizeof(long));
    crc = crc32(crc, (unsigned char *) &deepSleepStartSec,      sizeof(long));
    crc = crc32(crc, (unsigned char *) &lowPowerActiveTimeSec,  sizeof(long));
    crc = crc32(crc, (unsigned char *) &lowPowerPowerOnTimeSec, sizeof(long));
    crc = crc32(crc, (unsigned char *) &lastBme280ReadSec,      sizeof(long));
    crc = crc32(crc, (unsigned char *) &lastSmsCheckSec,        sizeof(long));
    crc = crc32(crc, (unsigned char *) &lastGpsReadSec,         sizeof(long));
    crc = crc32(crc, (unsigned char *) &lastMqttPublishSec,     sizeof(long));
    crc = crc32(crc, (unsigned char *) &mqttSendCount,          sizeof(long));
    crc = crc32(crc, (unsigned char *) &mqttLastSentTime,       sizeof(long));
    return crc;
 }
bool MyData::RtcData::isValid ()
Does the CRC fit s the content
Definition at line 133 of file Data.h.
References crcValue, and getCRC().
Referenced by MyDeepSleep::begin().
 {
    return getCRC() == crcValue;
 }
void MyData::RtcData::setCRC ()
Creates the CRC of all the data and save it in the class.
Definition at line 139 of file Data.h.
Referenced by MyDeepSleep::sleep().
 {
    crcValue = getCRC();
 }
The documentation for this class was generated from the following file:
tracker/Data.h