Snorktracker: MyLocation Class Reference
MyLocation Class Reference
#include <Gps.h>
Public Member Functions
void clear ()
double latitude ()
double longitude ()
String longitudeString ()
String latitudeString ()
double distanceTo (MyLocation &location)
double courseTo (MyLocation &location)
Static Public Member Functions
static double distanceBetween (double lat1, double long1, double lat2, double long2)
static double courseTo (double lat1, double long1, double lat2, double long2)
Protected Attributes
MyDegrees latitude_
Latitude.
MyDegrees longitude_
Longitude.
Friends
class MyGps
Detailed Description
Class to store the two gps positions
Definition at line 46 of file Gps.h.
Member Function Documentation
void MyLocation::clear ()
Reset the values.
Definition at line 241 of file Gps.h.
References MyDegrees::clear(), latitude_, and longitude_.
Referenced by MyGps::clear().
 {
    latitude_.clear();
    longitude_.clear();
 }
double MyLocation::courseTo (double lat1, double long1, double lat2, double long2) static
Calculate the course between two gps positions
Definition at line 274 of file Gps.h.
Referenced by courseTo().
 {
    // returns course in degrees (North=0, West=270) from position 1 to position 2,
    // both specified as signed decimal-degrees latitude and longitude.
    // Because Earth is no exact sphere, calculated course may be off by a tiny fraction.
    // Courtesy of Maarten Lamers
    double dlon = radians(long2 - long1);
    lat1 = radians(lat1);
    lat2 = radians(lat2);
    double a1 = sin(dlon) * cos(lat2);
    double a2 = sin(lat1) * cos(lat2) * cos(dlon);
    a2 = cos(lat1) * sin(lat2) - a2;
    a2 = atan2(a1, a2);
    if (a2 < 0.0)
    {
       a2 += TWO_PI;
    }
    return degrees(a2);
 }
double MyLocation::courseTo (MyLocation & to)
Calculate the course to another gps location
Definition at line 325 of file Gps.h.
References courseTo(), latitude(), and longitude().
 {
    return courseTo(latitude(), longitude(), to.latitude(), to.longitude());
 }
double MyLocation::distanceBetween (double lat1, double long1, double lat2, double long2) static
Calculate the distance between two gps positions in meter
Definition at line 248 of file Gps.h.
Referenced by distanceTo().
 {
    // returns distance in meters between two positions, both specified
    // as signed decimal-degrees latitude and longitude. Uses great-circle
    // distance computation for hypothetical sphere of radius 6372795 meters.
    // Because Earth is no exact sphere, rounding errors may be up to 0.5%.
    // Courtesy of Maarten Lamers
    double delta = radians(long1 - long2);
    double sdlong = sin(delta);
    double cdlong = cos(delta);
    lat1 = radians(lat1);
    lat2 = radians(lat2);
    double slat1 = sin(lat1);
    double clat1 = cos(lat1);
    double slat2 = sin(lat2);
    double clat2 = cos(lat2);
    delta = (clat1 * slat2) - (slat1 * clat2 * cdlong);
    delta = sq(delta);
    delta += sq(clat2 * sdlong);
    delta = sqrt(delta);
    double denom = (slat1 * slat2) + (clat1 * clat2 * cdlong);
    delta = atan2(delta, denom);
    return delta * 6372795;
 }
double MyLocation::distanceTo (MyLocation & to)
Calculate the distance between to another gps location
Definition at line 319 of file Gps.h.
References distanceBetween(), latitude(), and longitude().
Referenced by MyGsmGps::getGps(), and MyGsmGps::getGpsFromGsm().
 {
    return distanceBetween(latitude(), longitude(), to.latitude(), to.longitude());
 }
double MyLocation::latitude ()
Gets the latitude
Definition at line 295 of file Gps.h.
References latitude_, and MyDegrees::value().
Referenced by courseTo(), distanceTo(), MyGsmGps::getGps(), MyGsmGps::getGpsFromGsm(), and latitudeString().
 {
    return latitude_.value();
 }
String MyLocation::latitudeString ()
Returns the latitude as a string
Definition at line 313 of file Gps.h.
References latitude().
Referenced by MyGps::latitudeString().
 {
    return String(latitude(), 6);
 }
double MyLocation::longitude ()
Gets the Longitude
Definition at line 301 of file Gps.h.
References longitude_, and MyDegrees::value().
Referenced by courseTo(), distanceTo(), and longitudeString().
 {
    return longitude_.value();
 }
String MyLocation::longitudeString ()
Returns the longitude as a string
Definition at line 307 of file Gps.h.
References longitude().
Referenced by MyGps::longitudeString().
 {
    return String(longitude(), 6);
 }
The documentation for this class was generated from the following file:
tracker/Gps.h