Snorktracker: StringList Class Reference
StringList Class Reference
#include <StringList.h>
Public Member Functions
bool isEmpty ()
int count ()
int rolledOut ()
void removeAll ()
String getAt (int idx)
void addTail (String newInfo)
String removeHead ()
String removeTail ()
Data Fields
String infos
All the items in one string.
int infosCount
Number of items in the list.
int infosRolledOut
Number of items rolled out.
Detailed Description
String List class. Internally all items are stored in one string with '\1' as separator. The list has a maximum internal storage. While appending items it deletes automatically from the beginning until it fits. The performance could be optimized.
Definition at line 34 of file StringList.h.
Member Function Documentation
void StringList::addTail (String newInfo)
Append one item at the end of the list. If the list-string is too big then first items are deleted until it fits.
Definition at line 112 of file StringList.h.
References infos, infosCount, MAX_LOG_INFOS_SIZE, and removeHead().
Referenced by MyWebServer::handleLoadConsoleInfo(), myDebugInfo(), MySerial::read(), and MySerial::write().
 {
    while (infos.length() + newInfo.length() + 1 > MAX_LOG_INFOS_SIZE) {
       removeHead();
    }
    infos += newInfo;
    infos += '\1';
    infosCount++;
 }
int StringList::count ()
How many items are in the list?
Definition at line 72 of file StringList.h.
References infosCount.
Referenced by MyWebServer::handleLoadConsoleInfo().
 {
    return infosCount;
 }
String StringList::getAt (int idx)
Returns the n'th item from the list.
Definition at line 92 of file StringList.h.
References infos.
Referenced by MyWebServer::handleLoadConsoleInfo().
 {
    int currIdx = 0;
    int lastPos = 0;
    for(int i = 0; i < infos.length(); i++) {
       if (infos[i] == '\1') {
          if (currIdx == idx) {
             return infos.substring(lastPos, i);
          }
          lastPos = i + 1;
          currIdx++;
       }
    }
    return "";
 }
bool StringList::isEmpty ()
Is the list empty?
Definition at line 66 of file StringList.h.
References infosCount.
Referenced by loop().
 {
    return infosCount == 0;
 }
void StringList::removeAll ()
Removes all items from the list.
Definition at line 84 of file StringList.h.
References infos, infosCount, and infosRolledOut.
Referenced by MyWebServer::loadConsole().
 {
    infos          = "";
    infosCount     = 0;
    infosRolledOut = 0;
 }
String StringList::removeHead ()
Remove the first item from the list.
Definition at line 123 of file StringList.h.
References infos, infosCount, and infosRolledOut.
Referenced by addTail(), and loop().
 {
    String ret;
    int    idx = infos.indexOf('\1');
    if (idx != -1) {
       ret   = infos.substring(0, idx);
       infos = infos.substring(idx + 1);
       infosCount--;
       infosRolledOut++;
    }
    return ret;
 }
String StringList::removeTail ()
Removes the last item from the list.
Definition at line 138 of file StringList.h.
References infos, and infosCount.
Referenced by myDebugInfo().
 {
    String ret;
    for (int i = infos.length() - 1; i >= 0; i--) {
       if (infos[i] == '\1') {
          ret   = infos.substring(i + 1);
          infos = infos.substring(0, i);
          infosCount--;
          break;
       }
    }
    return ret;
 }
int StringList::rolledOut ()
How many items are in the list?
Definition at line 78 of file StringList.h.
References infosRolledOut.
Referenced by MyWebServer::handleLoadConsoleInfo().
 {
    return infosRolledOut;
 }
The documentation for this class was generated from the following file:
tracker/StringList.h