Snorktracker: MyGsmGps Class Reference
MyGsmGps Class Reference
#include <GsmGps.h>
Public Member Functions
MyGsmGps (MyOptions &options, MyData &data, short pinRx, short pinTx)
bool begin ()
void handleClient ()
bool stop ()
bool waitingForGps ()
bool sendAT (String cmd)
bool getSMS (SmsData &sms)
bool sendSMS (String phoneNumber, String message)
bool deleteSMS (long index)
Data Fields
MySerial gsmSerial
Serial interface to the sim808 modul.
MyGsmSim808 gsmSim808
SIM808 interface class.
TinyGsmClient gsmClient
Gsm client interface.
MyOptions & myOptions
Reference to the options.
MyData & myData
Reference to the data.
Protected Member Functions
void enableGps (bool enable)
bool getGps ()
bool getGpsFromGsm ()
bool sleepMode2 ()
Protected Attributes
long lastGsmChecSec
Check intervall for signal and battery quality.
long lastGpsCheckSec
GPS Check intervall.
long startGpsCheck
Timstamp of first getGps try.
Detailed Description
SIM808 Communication class to handle gprs and gps activities.
Definition at line 31 of file GsmGps.h.
Constructor & Destructor Documentation
MyGsmGps::MyGsmGps (MyOptions & options, MyData & data, short pinRx, short pinTx)
Constructor
Definition at line 70 of file GsmGps.h.
References gsmSerial.
    : gsmSerial(data.logInfos, options.isDebugActive, pinRx, pinTx)
    , gsmSim808(gsmSerial)
    , gsmClient(gsmSim808)
    , myOptions(options)
    , myData(data)
    , lastGsmChecSec(0)
    , lastGpsCheckSec(0)
    , startGpsCheck(0)
 {
    gsmSerial.begin(9600);
 }
Member Function Documentation
bool MyGsmGps::begin ()
Initialized the sim808 modul and start optionally the gsm and/ or gps part.
Definition at line 84 of file GsmGps.h.
References MyData::cop, enableGps(), MyOptions::gprsAP, MyOptions::gprsPassword, MyOptions::gprsUser, gsmSim808, MyData::imei, MyData::isGpsActive, MyOptions::isGpsEnabled, MyData::isGsmActive, MyData::modemInfo, MyData::modemIP, myData, MyDbg(), MyDelay(), myOptions, MyOptions::powerOn, and MyData::status.
Referenced by loop().
 {
    if (!myOptions.powerOn) {
       MyDbg(F("sim808 has no power!"));
       return false;
    }
    if (!myData.isGsmActive) {
       MyDbg(F("MyGsmGps::begin"));
       myData.status = F("Sim808 Initializing...");
       MyDbg(myData.status);
       for (int i = 0; !gsmSim808.restart() && i <= 5; i++) {
          if (!myOptions.powerOn) {
             MyDbg(F("Sim808 Initializing ... canceled"));
             return false;
          }
          if (i == 5) { // not working!
             myData.status = F("Sim808 restart failed");
             MyDbg(myData.status);
             return false;
          }
          MyDbg(F("."), false, false);
          MyDelay(500);
       }
       myData.status = F("Sim808 connected");
       MyDbg(myData.status);
       gsmSim808.setBaud(9600);
       myData.status = F("Sim808 Waiting for network...");
       MyDbg(myData.status);
       for (int i = 0; !gsmSim808.waitForNetwork() && i <= 5; i++) {
          if (!myOptions.powerOn) {
             MyDbg(F("Sim808 Waiting for network... canceled"));
             return false;
          }
          if (i == 5) { // not working!
             myData.status = F("Sim808 network failed");
             MyDbg(myData.status);
             return false;
          }
          MyDbg(F("."), false, false);
          MyDelay(500);
       }
       if (!gsmSim808.isNetworkConnected()) {
          myData.status = F("Sim808 network failed");
          MyDbg(myData.status);
       } else {
          myData.status = F("Sim808 network connected");
          MyDbg(myData.status);
          MyDbg((String) F("GPRS: ") + myOptions.gprsAP +
             F(" User: ") + myOptions.gprsUser + F(" Password: ") + myOptions.gprsPassword);
          if (!gsmSim808.gprsConnect(myOptions.gprsAP.c_str(), myOptions.gprsUser.c_str(), myOptions.gprsPassword.c_str())) {
             myData.status = F("Sim808 gprs connection failed!");
             MyDbg(myData.status);
             return false;
          }
          myData.status = F("Sim808 gsm connected");
          MyDbg(myData.status);
          myData.modemInfo = gsmSim808.getModemInfo();
          MyDbg((String) F("Modem info: ") + myData.modemInfo);
          myData.modemIP = gsmSim808.getLocalIP();
          MyDbg((String) F("Modem IP: ") + myData.modemIP);
          myData.imei = gsmSim808.getIMEI();
          MyDbg((String) F("sim808: ") + myData.modemInfo);
          myData.cop = gsmSim808.getOperator();
          MyDbg((String) F("cop: ") + myData.modemInfo);
       }
       myData.isGsmActive = true;
    }
    if (myData.isGsmActive && myOptions.isGpsEnabled && !myData.isGpsActive) {
       enableGps(true);
    }
    return true;
 }
bool MyGsmGps::deleteSMS (long index)
Delete one specific sms from the sim card.
Definition at line 292 of file GsmGps.h.
References MyGsmSim808::deleteSMS(), gsmSim808, MyData::isGsmActive, myData, and MyDbg().
Referenced by MySmsCmd::checkSms().
 {
    if (!myData.isGsmActive) {
       MyDbg(F("gsm not active!"));
       return false;
    }
    MyDbg((String) F("deleteSMS: ") + String(index));
    return gsmSim808.deleteSMS(index);
 }
void MyGsmGps::enableGps (bool enable) protected
Switch on the gps part of the sim808 modul.
Definition at line 304 of file GsmGps.h.
References gsmSim808, MyData::isGpsActive, MyData::isGsmActive, myData, MyDbg(), and MyData::status.
Referenced by begin(), handleClient(), and stop().
 {
    if (!myData.isGsmActive) {
       MyDbg(F("sim808 gsm not active!"));
       return;
    }
    if (enable) {
       gsmSim808.enableGPS();
       myData.status = F("Sim808 gps enabled!");
       MyDbg(myData.status);
       myData.isGpsActive = true;
    } else {
       gsmSim808.disableGPS();
       myData.status = F("Sim808 gps disabled!");
       MyDbg(myData.status);
       myData.isGpsActive = false;
    }
 }
bool MyGsmGps::getGps () protected
Read one gps position with the sim808 modul and save the values in the global data.
Definition at line 325 of file GsmGps.h.
References MyGps::altitudeString(), MyGps::courseString(), MyGps::date, MyDate::dateString(), MyLocation::distanceTo(), MyGsmSim808::getGps(), gsmSim808, MyData::isGpsActive, MyData::isGsmActive, MyData::isMoving, MyGps::kmphString(), MyData::RtcData::lastGps, MyData::lastGpsUpdateSec, MyLocation::latitude(), MyGps::latitudeString(), MyGps::location, MyGps::longitudeString(), MyOptions::minMovingDistance, MyData::movingDistance, myData, MyDbg(), myOptions, MyData::rtcData, MyGps::satellitesString(), secondsSincePowerOn(), MyGps::time, MyTime::timeString(), and MyData::waitingForGps.
Referenced by handleClient().
 {
    if (!myData.isGsmActive) {
       MyDbg(F("sim808 gsm not active!"));
       return false;
    }
    bool ret = false;
    if (myData.isGpsActive) {
       MyGps gps;
       myData.waitingForGps = true;
       if (gsmSim808.getGps(gps)) {
          myData.lastGpsUpdateSec = secondsSincePowerOn();
          MyDbg((String) F("(gps) longitude: ")  + gps.longitudeString());
          MyDbg((String) F("(gps) latitude: ")   + gps.latitudeString());
          MyDbg((String) F("(gps) altitude: ")   + gps.altitudeString());
          MyDbg((String) F("(gps) kmph: ")       + gps.kmphString());
          MyDbg((String) F("(gps) satellites: ") + gps.satellitesString());
          MyDbg((String) F("(gps) course: ")     + gps.courseString());
          MyDbg((String) F("(gps) gpsDate: ")    + gps.date.dateString());
          MyDbg((String) F("(gps) gpsTime: ")    + gps.time.timeString());
          if (myData.rtcData.lastGps.location.latitude() != 0) {
             myData.movingDistance = gps.location.distanceTo(myData.rtcData.lastGps.location);
             myData.isMoving       = myData.movingDistance > myOptions.minMovingDistance;
          }
          myData.rtcData.lastGps = gps;
          myData.waitingForGps   = false;
          ret = true;
       } else {
          MyDbg(F(" -> GPS timeout!"));
       }
    }
    return ret;
 }
bool MyGsmGps::getGpsFromGsm () protected
Get the Gps position from the gsm modul as fallback.
Definition at line 365 of file GsmGps.h.
References MyGps::date, MyDate::dateString(), MyLocation::distanceTo(), MyGsmSim808::getGsmGps(), gsmSim808, MyData::isGsmActive, MyData::isMoving, MyData::RtcData::lastGps, MyData::lastGpsUpdateSec, MyLocation::latitude(), MyGps::latitudeString(), MyGps::location, MyGps::longitudeString(), MyOptions::minMovingDistance, MyData::movingDistance, myData, MyDbg(), myOptions, MyData::rtcData, secondsSincePowerOn(), MyGps::time, and MyTime::timeString().
Referenced by handleClient().
 {
    if (!myData.isGsmActive) {
       MyDbg(F("sim808 gsm not active!"));
       return false;
    }
    MyGps gps;
    // Get the GPS position as fallback from the GSM modul.
    MyDbg(F("getGsmGps"));
    if (gsmSim808.getGsmGps(gps)) {
       myData.lastGpsUpdateSec = secondsSincePowerOn();
       MyDbg((String) F("(gsmGps) longitude: ") + gps.longitudeString());
       MyDbg((String) F("(gsmGps) latitude: ")  + gps.latitudeString());
       MyDbg((String) F("(gsmGps) gpsDate: ")   + gps.date.dateString());
       MyDbg((String) F("(gsmGps) gpsTime: ")   + gps.time.timeString());
       if (myData.rtcData.lastGps.location.latitude() != 0) {
          myData.movingDistance = gps.location.distanceTo(myData.rtcData.lastGps.location);
          myData.isMoving       = myData.movingDistance > myOptions.minMovingDistance;
       }
       myData.rtcData.lastGps = gps;
       return true;
    } else {
       MyDbg(F(" -> GsmGPS timeout!"));
    }
    return false;
 }
bool MyGsmGps::getSMS (SmsData & sms)
Read one sms if available.
Definition at line 268 of file GsmGps.h.
References MyGsmSim808::getSMS(), gsmSim808, MyData::isGsmActive, myData, and MyDbg().
Referenced by MySmsCmd::checkSms().
 {
    if (!myData.isGsmActive) {
       MyDbg(F("gsm not active!"));
       return false;
    }
    MyDbg(F("getSMS"));
    return gsmSim808.getSMS(sms);
 }
void MyGsmGps::handleClient ()
Checks the gps from time to time if enabled.
Definition at line 168 of file GsmGps.h.
References MyData::batteryLevel, MyData::batteryVolt, enableGps(), getGps(), getGpsFromGsm(), MyOptions::gpsCheckIntervalSec, MyOptions::gpsTimeoutSec, gsmSim808, MyData::isGpsActive, MyData::isGsmActive, lastGpsCheckSec, MyData::RtcData::lastGpsReadSec, lastGsmChecSec, myData, MyDbg(), myOptions, MyData::rtcData, secondsElapsed(), secondsElapsedAndUpdate(), secondsSincePowerOn(), MyData::signalQuality, startGpsCheck, and MyData::waitingForGps.
Referenced by loop().
 {
    if (!myData.isGsmActive) {
       return;
    }
    if (secondsElapsedAndUpdate(lastGsmChecSec, 60000)) { // Check every minute
       myData.signalQuality = String(gsmSim808.getSignalQuality());
       myData.batteryLevel  = String(gsmSim808.getBattPercent());
       myData.batteryVolt   = String(gsmSim808.getBattVoltage() / 1000.0F, 2);
       MyDbg((String) F("(sim808) signalQuality: ") + myData.signalQuality);
       MyDbg((String) F("(sim808) batteryLevel: ")  + myData.batteryLevel);
       MyDbg((String) F("(sim808) batteryVolt: ")   + myData.batteryVolt);
    }
    if (secondsElapsedAndUpdate(lastGpsCheckSec, 10)) { // Wait 10 sec between retries
       if (secondsElapsed(myData.rtcData.lastGpsReadSec, myOptions.gpsCheckIntervalSec)) {
          if (!myData.isGpsActive) {
             enableGps(true);
          }
          MyDbg(F("getGPS"));
          if (startGpsCheck == 0) {
             startGpsCheck = secondsSincePowerOn();
          }
          if (getGps()) {
             MyDbg(F(" -> ok"));
             startGpsCheck = 0;
             myData.rtcData.lastGpsReadSec = secondsSincePowerOn();
          } else {
             long waitForGpsTime = secondsSincePowerOn() - startGpsCheck;
             // Ignore gps if we cannot get a position in X minutes.
             if (waitForGpsTime > myOptions.gpsTimeoutSec) {
                getGpsFromGsm(); // fallback from gsm
                MyDbg(F(" -> gps timeout!"));
                startGpsCheck = 0;
                myData.waitingForGps = false;
                myData.rtcData.lastGpsReadSec = secondsSincePowerOn();
             } else {
                if (myOptions.gpsTimeoutSec - waitForGpsTime > 0) {
                   MyDbg((String) F(" -> no gps fix (timeout in ") + String(myOptions.gpsTimeoutSec - waitForGpsTime) + F(" seconds!)"));
                }
             }
          }
       }
    }
 }
bool MyGsmGps::sendAT (String cmd)
Send one AT command to the sim modul and log the result for the console window.
Definition at line 244 of file GsmGps.h.
References gsmSerial, gsmSim808, MyData::isGsmActive, myData, and MyDbg().
Referenced by loop(), and sleepMode2().
 {
    if (!myData.isGsmActive) {
       MyDbg(F("sim808 not active!"));
       return false;
    }
    String response;
    gsmSerial.print(cmd);
    gsmSerial.print(F("\r\n"));
    gsmSim808.waitResponse(1000, response);
    MyDbg(response);
    return true;
 }
bool MyGsmGps::sendSMS (String phoneNumber, String message)
Send one sms to a specific phone number via gsm.
Definition at line 280 of file GsmGps.h.
References gsmSim808, MyData::isGsmActive, myData, and MyDbg().
Referenced by MySmsCmd::sendSms().
 {
    if (!myData.isGsmActive) {
       MyDbg(F("gsm not active!"));
       return false;
    }
    MyDbg((String) F("sendSMS: ") + message);
    return gsmSim808.sendSMS(phoneNumber, message);
 }
bool MyGsmGps::sleepMode2 () protected
Entering the power save mode of the sim808 modul.
Definition at line 261 of file GsmGps.h.
References MyDbg(), and sendAT().
Referenced by stop().
 {
    MyDbg(F("Entering gsm sleep mode 2"));
    return sendAT(GF("+CSCLK=2"));
 }
bool MyGsmGps::stop ()
Stops the sim808 modul and go to deep sleep mode.
Definition at line 219 of file GsmGps.h.
References enableGps(), gsmSim808, MyData::isGsmActive, myData, MyDbg(), sleepMode2(), and MyData::status.
Referenced by loop().
 {
    bool ret = true;
    MyDbg(F("gprs gps stopping"));
    enableGps(false);
    if (gsmSim808.isGprsConnected()) {
       ret = gsmSim808.gprsDisconnect();
    }
    if (ret) {
       myData.isGsmActive = false;
       MyDbg(F("gprs gps stopped"));
       myData.status = F("Sim808 stopped!");
       sleepMode2();
    }
    return ret;
 }
bool MyGsmGps::waitingForGps ()
Is the gps enabled but we don't have a valid gps position.
Definition at line 238 of file GsmGps.h.
References MyOptions::isGpsEnabled, MyData::isGsmActive, myData, myOptions, and MyData::waitingForGps.
Referenced by loop().
 {
    return myData.isGsmActive && myOptions.isGpsEnabled && myData.waitingForGps;
 }
The documentation for this class was generated from the following file:
tracker/GsmGps.h