Snorktracker: MyDate Class Reference
MyDate Class Reference
#include <Gps.h>
Public Member Functions
int year ()
int month ()
int day ()
void clear ()
String dateString ()
Protected Attributes
int date
Date in the form of YearMonthDay i.e. 20170115.
Friends
class MyGps
Detailed Description
Class to store the date with an integer.
Definition at line 73 of file Gps.h.
Member Function Documentation
void MyDate::clear ()
Reset the values.
Definition at line 331 of file Gps.h.
References date.
Referenced by MyGps::clear().
 {
    date = 0;
 }
String MyDate::dateString ()
Returns the gps date as a string
Definition at line 355 of file Gps.h.
References day(), month(), and year().
Referenced by MyGsmGps::getGps(), MyGsmGps::getGpsFromGsm(), and MyWebServer::handleLoadInfoInfo().
 {
    return String(day()) + '-' + String(month()) + '-' + String(year());
 }
int MyDate::day ()
Gets the day from the date
Definition at line 349 of file Gps.h.
References date.
Referenced by dateString().
 {
    return date % 100;
 }
int MyDate::month ()
Gets the Month from the date
Definition at line 343 of file Gps.h.
References date.
Referenced by dateString().
 {
    return (date / 100) % 100;
 }
int MyDate::year ()
Gets the year from the date
Definition at line 337 of file Gps.h.
References date.
Referenced by dateString().
 {
    return date / 10000;
 }
The documentation for this class was generated from the following file:
tracker/Gps.h