Snorktracker: MyTime Class Reference
MyTime Class Reference
#include <Gps.h>
Public Member Functions
int hour ()
int minute ()
int second ()
MyTime (int t)
void clear ()
String timeString ()
operator int ()
Protected Attributes
int time
Time in the form of HoursMinutesSecons i.e. 120135.
Friends
class MyGps
Detailed Description
Class to store the time with an integer
Definition at line 97 of file Gps.h.
Member Function Documentation
void MyTime::clear ()
Reset the values.
Definition at line 361 of file Gps.h.
References time.
Referenced by MyGps::clear().
 {
    time = 0;
 }
int MyTime::hour ()
Gets the hour from the time value
Definition at line 367 of file Gps.h.
References time.
Referenced by timeString().
 {
    return time / 10000;
 }
int MyTime::minute ()
Gets the minute from the time value
Definition at line 373 of file Gps.h.
References time.
Referenced by timeString().
 {
    return (time / 100) % 100;
 }
int MyTime::second ()
Gets the seconds from the time value
Definition at line 379 of file Gps.h.
References time.
Referenced by timeString().
 {
    return time % 100;
 }
String MyTime::timeString ()
Returns the gps time as a string
Definition at line 385 of file Gps.h.
References hour(), minute(), and second().
Referenced by MyGsmGps::getGps(), MyGsmGps::getGpsFromGsm(), MyWebServer::handleLoadInfoInfo(), and MyWebServer::handleLoadMainInfo().
 {
    return String(hour()) + ':' + String(minute()) + ':' + String(second());
 }
The documentation for this class was generated from the following file:
tracker/Gps.h