Snorktracker: MyBME280 Class Reference
MyBME280 Class Reference
#include <BME280.h>
Public Member Functions
MyBME280 (MyOptions &options, MyData &data, int pin, uint8_t addr)
bool begin ()
bool readValues ()
Protected Attributes
MyOptions & myOptions
Reference to global options.
MyData & myData
Reference to global data.
int pinGrnd
Ground-Pin connection to switch on the BME280 module.
uint8_t portAddr
Port address of the bme280.
Adafruit_BME280 bme280
Adafruit BME280 helper interface.
Detailed Description
Communication with the BME280 modul to read temperature, humidity and pressure
Definition at line 32 of file BME280.h.
Constructor & Destructor Documentation
MyBME280::MyBME280 (MyOptions & options, MyData & data, int pin, uint8_t addr)
Constructor
Definition at line 52 of file BME280.h.
    : pinGrnd(pin)
    , myOptions(options)
    , myData(data)
    , portAddr(addr)
 {
 }
Member Function Documentation
bool MyBME280::begin ()
Switch off the module at startup to safe power.
Definition at line 61 of file BME280.h.
References pinGrnd.
Referenced by setup().
 {
    pinMode(D1,      INPUT); // I2C SCL Open state to safe power
    pinMode(D2,      INPUT); // I2C SDA Open state to safe power
    pinMode(pinGrnd, OUTPUT);
    digitalWrite(pinGrnd, HIGH);
 }
bool MyBME280::readValues ()
Switch on the modul, read the values and switch off the modul to save power. Do this only every bme280CheckIntervalSec
Definition at line 73 of file BME280.h.
References BARO_CORR_HPA, bme280, MyOptions::bme280CheckIntervalSec, MyData::humidity, MyData::RtcData::lastBme280ReadSec, myData, MyDbg(), myOptions, pinGrnd, portAddr, MyData::pressure, MyData::rtcData, secondsElapsedAndUpdate(), TEMP_CORR_DEGREE, and MyData::temperature.
Referenced by loop().
 {
    if (secondsElapsedAndUpdate(myData.rtcData.lastBme280ReadSec, myOptions.bme280CheckIntervalSec)) {
       digitalWrite(pinGrnd, LOW);
       delay(100); // Short delay after power on
       if (!bme280.begin(portAddr)) {
          myData.temperature = 0;
          myData.humidity    = 0;
          myData.pressure    = 0;
          MyDbg("No valid BME280 sensor, check wiring!");
       } else {
          myData.temperature = bme280.readTemperature() + TEMP_CORR_DEGREE;
          myData.humidity    = bme280.readHumidity();
          myData.pressure    = (bme280.readPressure() / 100.0F) + BARO_CORR_HPA;
          MyDbg("Temperature: " + String(myData.temperature) + "°C");
          MyDbg("Humidity: "    + String(myData.humidity)    + "%");
          MyDbg("Pressure: "    + String(myData.pressure)    + "hPa");
       }
       digitalWrite(pinGrnd, HIGH);
       pinMode(D1, INPUT); // I2C SCL Open state to safe power
       pinMode(D2, INPUT); // I2C SDA Open state to safe power
    }
 }
The documentation for this class was generated from the following file:
tracker/BME280.h