Snorktracker: MyGsmSim808 Class Reference
MyGsmSim808 Class Reference
#include <Sim808.h>
Public Member Functions
MyGsmSim808 (Stream &stream)
bool getGps (MyGps &gps)
bool getGsmGps (MyGps &gps)
bool getSMS (SmsData &sms)
bool deleteSMS (long index)
Detailed Description
Extension class of the TinyGsmSim808 base class. Implements the special gps call and some sms functions.
Definition at line 47 of file Sim808.h.
Constructor & Destructor Documentation
MyGsmSim808::MyGsmSim808 (Stream & stream)
Constructor
Definition at line 61 of file Sim808.h.
    : TinyGsmSim808(stream)
 {
 }
Member Function Documentation
bool MyGsmSim808::deleteSMS (long index)
Delete a specific sms from the sim card.
Definition at line 164 of file Sim808.h.
Referenced by MyGsmGps::deleteSMS().
 {
    sendAT(GF("+CMGD=") + String(index));
    if (waitResponse() != 1) {
       return false;
    }
    return true;
 }
bool MyGsmSim808::getGps (MyGps & gps)
Read and parse a gps information from the sim808 modul in the own MyGps data class
Definition at line 67 of file Sim808.h.
References MyGps::clear(), MyGps::fixStatus, MyGps::setAltitude(), MyGps::setCourse(), MyGps::setDateTime(), MyGps::setFixMode(), MyGps::setFixStatus(), MyGps::setHdop(), MyGps::setLatitude(), MyGps::setLongitude(), MyGps::setPdop(), MyGps::setRunStatus(), MyGps::setSatellitesInView(), MyGps::setSatellitesUsed(), MyGps::setSpeed(), and MyGps::setVdop().
Referenced by MyGsmGps::getGps().
 {
    gps.clear();
    sendAT(GF("+CGNSINF"));
    if (waitResponse(GF(GSM_NL "+CGNSINF:")) != 1) {
       return false;
    }
    gps.setRunStatus        (stream.readStringUntil(','));
    gps.setFixStatus        (stream.readStringUntil(','));
    gps.setDateTime         (stream.readStringUntil(','));
    gps.setLatitude         (stream.readStringUntil(','));
    gps.setLongitude        (stream.readStringUntil(','));
    gps.setAltitude         (stream.readStringUntil(','));
    gps.setSpeed            (stream.readStringUntil(','));
    gps.setCourse           (stream.readStringUntil(','));
    gps.setFixMode          (stream.readStringUntil(','));
    /* reserved */          (stream.readStringUntil(','));
    gps.setHdop             (stream.readStringUntil(','));
    gps.setPdop             (stream.readStringUntil(','));
    gps.setVdop             (stream.readStringUntil(','));
    /* reserved */          (stream.readStringUntil(','));
    gps.setSatellitesInView (stream.readStringUntil(','));
    gps.setSatellitesUsed   (stream.readStringUntil(','));
    stream.readStringUntil('\n');
    waitResponse();
    return gps.fixStatus;
 }
bool MyGsmSim808::getGsmGps (MyGps & gps)
Read and parse a gsm-gps information from the sim808 modul in the own MyGps data class Sample: AT+CIPGSMLOC=1,1 +CIPGSMLOC: 0,23.7798,61.496052,2019/01/26,08:21:47
Definition at line 102 of file Sim808.h.
References MyGps::clear(), MyGps::fixStatus, MyGps::setDateTime(), MyGps::setLatitude(), and MyGps::setLongitude().
Referenced by MyGsmGps::getGpsFromGsm().
 {
    gps.clear();
    sendAT(GF("+CIPGSMLOC=1,1"));
    if (waitResponse(10000L, GF(GSM_NL "+CIPGSMLOC:")) != 1) {
       return false;
    }
    String locationCode = stream.readStringUntil(',');
    String longitude    = stream.readStringUntil(',');
    String latitude     = stream.readStringUntil(',');
    String gsmDate      = stream.readStringUntil(',');
    String gsmTime      = stream.readStringUntil(',');
    stream.readStringUntil('\n');
    waitResponse();
    locationCode.trim();
    if (locationCode == "0") {
       String dateTime = gsmDate + gsmTime;
       dateTime.replace("/", "");
       dateTime.replace(":", "");
       dateTime += ".000";
       gps.setLatitude(latitude);
       gps.setLongitude(longitude);
       gps.setDateTime(dateTime);
       gps.fixStatus = true;
    }
    return gps.fixStatus;
 }
bool MyGsmSim808::getSMS (SmsData & sms)
Read one SMS from the sim card into the own SmsData class.
Definition at line 136 of file Sim808.h.
References SmsData::dateTime, SmsData::index, SmsData::message, SmsData::phoneNumber, SmsData::referenceNumber, SmsData::status, and Trim().
Referenced by MyGsmGps::getSMS().
 {
    // PDU Mode (Hex)
    sendAT(GF("+CMGF=1"));
    if (waitResponse() != 1) {
       return false;
    }
    // Read unread sms
    sendAT(GF("+CMGL=\"REC UNREAD\""));
    int status = waitResponse(GFP(GSM_OK), GF("+CMGL:"));
    if (status == 2) {
       sms.index           = atoi(stream.readStringUntil(',').c_str());
       sms.status          = stream.readStringUntil(',');
       sms.phoneNumber     = stream.readStringUntil(',');
       sms.referenceNumber = stream.readStringUntil(',');
       sms.dateTime        = stream.readStringUntil('\n');
       sms.message         = stream.readStringUntil('\n');
       sms.message         = Trim(sms.message, F("\r\n"));
       waitResponse();
       return true;
    }
    return false;
 }
The documentation for this class was generated from the following file:
tracker/Sim808.h